name: NekoFetcher
version: 0.2
author: Vz0n
api-version: 1.13
main: io.github.Vz0n.neko.NekoFetcher
description: 'Get neko images in your maps.'
commands:
  nget:
    aliases: [nekoget]
    description: "Get a neko image"
    permission: "nekofetcher.get"
  neko:
    aliases: [nekofetcher, neko]
    description: "Main NekoFetcher command."
    permission: "nekofetcher.neko"
    
